# travis-ci.org build & test configuration
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download
    - $HOME/miniconda2

language: python

python:
  - "2.7"
  - "3.6"

env:
  - CI_RUN_TEST=UNIT CI_RUN_CONFIG=NONE
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=all2017
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=demo
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=efficiencies
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=offline_met_studies
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rates
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rateVsPU
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=weekly_checks
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=gen
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=study_tower28_met

before_install:
  - export CMSL1T_CONDA_PATH=$HOME/miniconda2
  - ./.ci/before_install.sh
  - export PATH=${CMSL1T_CONDA_PATH}/bin:$PATH
  - export NO_CVMFS=1

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh

cache: apt

addons:
  apt:
    packages:
    - build-essential
    - python-psutil
