# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms
  - docker pull kreczko/cms-l1t-analysis:travis

install:
  - docker run -d -v $PWD:/analysis --privileged=true --name=cmsl1t_test kreczko/cms-l1t-analysis:travis
  - docker ps -a
  - echo "Waiting for CVMFS to start up"
  - sleep 30

script:
  - docker exec -t cmsl1t_test /bin/bash -c 'source /ci/test.sh'

after_script:
  - docker stop cmsl1t_test
cache: apt
