# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms
  - docker pull kreczko/cms-l1t-analysis:travis

script:
  - sudo docker run -t -v $PWD:/analysis --privileged=true kreczko/cms-l1t-analysis:travis
cache: apt
