# travis-ci.org build & test configuration
services:
  - docker

language: python

env:
  - CI_RUN_TEST=UNIT CI_RUN_CONFIG=NONE
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=all2017
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=demo
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=efficiencies
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=offline_met_studies
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rates
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rateVsPU
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=weekly_checks
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=gen
  - CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=study_tower28_met

before_install:
  - docker pull cmsl1tanalysis/cmsl1t-dev:v6-18-04
  - docker run -d --name cms -v $PWD:/opt/cms-l1t-analysis cmsl1tanalysis/cmsl1t-dev:v6-18-04 bash
  - docker ps -a
  - docker exec cms bash -c "python -m pip install -r /opt/cms-l1t-analysis/requirements.txt"

script:
  - docker exec -e CI_RUN_TEST=$CI_RUN_TEST -e CI_RUN_CONFIG=$CI_RUN_CONFIG cms bash -c "cd /opt/cms-l1t-analysis; ./.ci/test.sh"
