# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms

install:
 - cd ci
 - sudo docker build -t cms-l1t-offline/cms-l1t-analysis .
 - cd -

script:
  - sudo docker run -t -v $PWD:/analysis --privileged cms-l1t-offline/cms-l1t-analysis
cache: apt
