# travis-ci.org build & test configuration
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download
    - /software/cmsl1t/miniconda

language: python

services:
  - docker

before_install:
  - export CMSL1T_CONDA_PATH=/software/cmsl1t/miniconda
  - ./.ci/before_install.sh
  - export PATH=${CMSL1T_CONDA_PATH}/bin:$PATH

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh

matrix:
  include:
    - env: CI_RUN_TEST=UNIT CI_RUN_CONFIG=NONE
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=all2017
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=demo
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=efficiencies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=offline_met_studies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rates
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rateVsPU
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=weekly_checks
  # currently no Generator or MuonReco test file
  allow_failures:
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=gen
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=study_tower28_met
cache: apt
