# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull kreczko/cms-l1t-analysis:ci

install:
  - source ci/mapping.sh
  - docker-compose build ci

script:
  - docker-compose up --exit-code-from ci ci

matrix:
  include:
    - env: CI_RUN_TEST=UNIT CI_RUN_CONFIG=NONE
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=all2017
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=demo
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=efficiencies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=offline_met_studies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rates
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rateVsPU
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=weekly_checks
  # currently no Generator or MuonReco test file
  allow_failures:
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=gen
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=study_tower28_met
cache: apt
