# travis-ci.org build & test configuration
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download
    - $HOME/miniconda2

language: python

before_install:
  - export CMSL1T_CONDA_PATH=$HOME/miniconda2
  - ./.ci/before_install.sh
  - export PATH=${CMSL1T_CONDA_PATH}/bin:$PATH
  - export NO_CVMFS=1

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh

matrix:
  include:
    - env: CI_RUN_TEST=UNIT CI_RUN_CONFIG=NONE
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=all2017
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=demo
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=efficiencies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=offline_met_studies
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rates
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=rateVsPU
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=weekly_checks
  # currently no Generator or MuonReco test file
  allow_failures:
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=gen
    - env: CI_RUN_TEST=INTEGRATION CI_RUN_CONFIG=study_tower28_met
cache: apt

addons:
  apt:
    packages:
    - build-essential
