version: '3'
services:
  cmsl1t:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: kreczko/cms-l1t-analysis
    volumes:
      - .:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: ${DISPLAY}
      TERM: ${TERM}
    working_dir: /code
    tty: true
    domainname: foo.bar
    hostname: cmsl1t

  ci:
    build:
      context: .
      dockerfile: ci/Dockerfile
      args:
        USERID: ${USERID}
    image: kreczko/cms-l1t-analysis:ci
    volumes:
      - .:/code
    environment:
      NO_CVMFS: 1
      CI_RUN_CONFIG: ${CI_RUN_CONFIG}
      CI_RUN_TEST: ${CI_RUN_TEST}
    working_dir: /code
    hostname: cmsl1t-ci
    privileged: true
