version: 1
name: Demo

input:
  files:
    # - data/L1Ntuple_*.root
    - test/data/2kmu.root
  sample:
    name: Data
    title: 2016 Data
  trigger:
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 276243

analysis:
  vectorized: True
  batch_size: 10000
  load_trees:
    - event
    - upgrade
    - recoTree
    - metFilterReco
    - caloTowers
    - emuCaloTowers
    - jetReco
  do_fit: False
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
    demo1:
      module: cmsl1t.analyzers.demo_analyzer
    demo2:
      module: cmsl1t.analyzers.demo_analyzer
  producers:
    l1MetNot28:
      module: cmsl1t.producers.met_vectorized
      inputs:
        - L1CaloTower_iphi
        - L1CaloTower_ieta
        - L1CaloTower_iet
      outputs:
        - l1MetNot28
      method: l1MetNot28
    l1MetNot28HF:
      module: cmsl1t.producers.met_vectorized
      inputs:
        - L1CaloTower_iphi
        - L1CaloTower_ieta
        - L1CaloTower_iet
      outputs:
        - l1MetNot28HF
      method: l1MetNot28HF

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template:
     - output/demo
     - "{date}_{sample_name}_run-{run_number}_{trigger_name}"
