version: 0.0.1
name: Energy_Sum_Efficiencies

input:
  files:
    - data/L1Ntuple_*.root
  sample:
    name: Data
    title: 2016 Data
  trigger:
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 276243

analysis:
  do_fit: False
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
    - cmsl1t.analyzers.energy_sums_efficiencies
  producers:
    - cmsl1t.producers.met:
        inputs:
          - L1CaloTower_iphi
          - L1CaloTower_ieta
          - L1CaloTower_iet
        outputs:
          - l1MetBERecalc
    - cmsl1t.producers.met:
        inputs:
          - emu_L1CaloTower_iphi
          - emu_L1CaloTower_ieta
          - emu_L1CaloTower_iet
        outputs:
          - l1MetBERecalcEmu

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template:
     - output/Energy_Sum_Efficiencies
     - "{date}_{sample_name}_run-{run_number}_{trigger_name}"
