version: 0.0.1
name: Jet_Efficiencies

input:
  files:
    - data/L1Ntuple_*.root
  sample:
    name: Data
    title: 2016 Data
  trigger:
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 276243

analysis:
  do_fit: False
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
    - cmsl1t.analyzers.jet_efficiencies
  producers:
    - cmsl1t.producers.jets:
        inputs:
          - L1Upgrade_*
        outputs:
          - l1Jets
    - cmsl1t.producers.jets:
        inputs:
          - Jet_*
        outputs:
          - goodRecoJets
        params:
          filter: cmsl1t.filters.jets.defaultJetFilter

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template:
     - output/Jet_Efficiencies
     - "{date}_{sample_name}_run-{run_number}_{trigger_name}"
