version: 0.0.1
name: Study_tower28_met

input:
  files:
    - data/L1Ntuple_*.root
  sample:
    name: Data
    title: 2016 Data
  trigger:
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 276243

analysis:
  do_fit: False
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
    - cmsl1t.analyzers.study_tower28_met
  producers:
    - cmsl1t.producers.met:
        inputs:
          - L1CaloTower_iphi
          - L1CaloTower_ieta
          - L1CaloTower_iet
        outputs:
          - l1MetNot28
        params:
          method: l1MetNot28
    - cmsl1t.producers.met:
        inputs:
          - L1CaloTower_iphi
          - L1CaloTower_ieta
          - L1CaloTower_iet
        outputs:
          - l1MetNot28HF
        params:
          method: l1MetNot28HF

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template:
     - output/Study_tower28_met
     - "{date}_{sample_name}_run-{run_number}_{trigger_name}"
